### ISSUE TITLE
Merge iqy-cdn and iqy?

### ISSUE THREAD

**Issue by winduser** [winduser/Surge-Rules#3]
@lujiajing1126 Why not merge iqy-cdn and iqy? Is there any reason that you happen to find?

**Comment by lujiajing1126** [comment]
In the `Iqiyi.list`, I use `DOMAIN-KEYWORD` command to match all `qiyi` related requests.

However, all `CDN` requests should be passed through directly. It is faster and more economic.

One way to get rid of this inconvenience is to find all `API` entries of `iqiyi` services, which may be
boring and time-consuming.

**Comment by winduser** [comment]
Understood. Issue closed.
